### ISSUE TITLE
Where can I find the datasets in the examples you gave?

### ISSUE THREAD

**Issue by willshi88** [johli/scrambler#3]
For example, in the scrambler_apa_example_make_gif:

#Load APA data and predictor
encoder = OneHotEncoder(seq_length=205, channel_map={'A' : 0, 'C' : 1, 'G' : 2, 'T' : 3})
data_path = '../analysis/apa/apa_doubledope_cached_set.pickle'
x_train, y_train, x_test, y_test = load_apa_data(data_path, encoder)
predictor_path = '../../aparent/saved_models/aparent_plasmid_iso_cut_distalpas_all_libs_no_sampleweights_sgd.h5'
predictor = load_apa_predictor(predictor_path)

But I cannot find the apa_doubledope_cached_set.pickle. 

Thanks

**Comment by jlinder2** [comment]
Hi,

I have now updated the Github so that it contains both the datasets and the tensorflow models for all example interpretation tasks. For example, in the subfolder 'examples/dna' you will now find the dataset 'apa_doubledope_cached_set.csv' that you asked for.

Let me know if you have any other requests or comments.

Best,

Johannes
