### ISSUE TITLE
multiple output with regression task

### ISSUE THREAD

**Issue by ofiryaish** [johli/scrambler#5]
Hello, 

During my testing, I'm trying to use the tool with model regression model which has multiple outputs  (8 outputs). I'm willing to get attribution scores for each output, similar to what we can achieve with Integrated Gradient. I noticed that one of the arguments is `n_classes`, which was probably designed for a classification task like you have in the Mnist example (there it seems that you got for each output attribution scores).  However, due to fact that I got an error without initializing this argument, I tried to initialize it with 8, and I succeed to run it. Does it valid?
This is the initialization and training of the scrambler:
```
#Initialize scrambler
scrambler = Scrambler(
    scrambler_mode='inclusion',
    n_classes=8,
    input_size_x=1,
    input_size_y=110,
    n_out_channels=4,
    input_templates=[onehot_template],
    input_backgrounds=[x_mean],
    batch_size=32,
    n_samples=32,
    sample_mode='st',
    zeropad_input=False,
    mask_dropout=False,
    network_config=network_config
)

train_history = scrambler.train(
    predictor,
    x_train[:67264],
    y_train[:67264],
    x_test[:32],
    y_test[:32],
    n_epochs,
    monitor_test_indices=np.arange(32).tolist(),
    #monitor_batch_freq_dict={0 : 1, 100 : 5, 469 : 10},
    nll_mode='minimization',
    predictor_task='regression',
    entropy_mode='target',
    entropy_bits=0.25,
    entropy_weight=1.
)
```

When I apply:
`pwm_test, sample_test, importance_scores_test = scrambler.interpret(x_test)`

I get that `importance_scores_test ` results scores which can't support scores per output but are suitable (in shape) for one output.  Can something be done? what is the meaning of those scores when there is one output?

Another question, can you explain what are the arguments `entropy_bits`,  `entropy_weight`, and how changing them should affect the results? In general, there are many arguments in code that their function is not clear.

Thank you for your time,
Ofir

**Comment by johli** [comment]
Hi Ofir,

Currently, the code works as follows: When choosing 'regression' as the predictor_task, the argument n_classes is not used for anything. Instead, what will happen is that the scrambler will optimize the mean objective taken across your 8 outputs (e.g. in your code example - the scrambler will find the features which minimize the average of the outputs).

Unfortunately, the code does not currently support choosing only one of the outputs (but it sounds valuable so I will try to implement this functionality in the next one or two weeks). A workaround with the current code version is to build 8 separate predictor models (instead of 1 predictor model with 8 outputs) and then train 8 individual scramblers (one for each output/predictor). I realize this gets messy but it's the only way to make that work before I launch new code changes.

Best,

Johannes

Ps., we are working on documenting input parameters etc. 'entropy_bits' controls the desired average per-nucleotide conservation for your sequence PWM (e.g. entropy_bits=0.25 will train a scrambler that outputs PWMs with on average 0.25 / 2.0 bits of conservation for each nucleotide position). The parameter 'entropy_weight' controls how strongly this average target is enforced (e.g. if entropy_weight=1.0, the the PWMs can deviate more away from 0.25 in average bits than if entropy_weight=10.0).

**Comment by ofiryaish** [comment]
As I suspected that it will do.

Thank you, I'm looking forward to the update
